### ISSUE TITLE
Problem Running Statemod for San Juan Basin 

### ISSUE THREAD

**Issue by rg727** [OpenCDSS/cdss-app-statemod-fortran#80]
### Subject of the issue ###

Hello! I'm trying to run the baseline input data for the San Juan Basin through the Fortran version of the Statemod model that is found here: https://github.com/antonia-had/cdss-app-statemod-fortran. We have had success running the Upper Colorado dataset and the Gunnison as examples, but there appears to be an issue with the San Juan dataset

### Environment ###

* StateMod version: Found here: https://github.com/antonia-had/cdss-app-statemod-fortran
* Operating system version: Linux

### Steps to reproduce ###

I successfully compiled the Fortran executable and then ran ./statemod sj2015B

### Expected Behavior ###

Model should run to completion.

### Actual Behavior ###

The model stops almost immediately with an indexing error shown here: 

<img width="570" alt="SJ2015error" src="https://user-images.githubusercontent.com/31748312/152834766-7e9c7e7e-8eb1-4d49-a22b-ee105f19621f.PNG">

**Comment by Rayrbennett** [comment]
Hello, 
The Linux version had a couple of hick-ups that got resolved during porting & most likely fixed your problem.  It’s hard to say if your run reflects the latest Linux version w/o a version #. 

Please let me know the Statemod version you are running (see top of file *.log) & i or others cc’d on this email will get you up & running ASAP.  

Ray

**Comment by rg727** [comment]
Hi Ray,

Thank you so much for your help. I'm attaching a screenshot here of the log
file.


[image: image.png]

Best,
Rohini

**Comment by Rayrbennett** [comment]
Sorry but I don’t see the screen shot. Please resend or get version # & date from the *.log file.  

Also, can you confirm where you got your data, if you made any changes, the type of run you are making (simulate, baseflow, check or report) & the response file (*.rsp) you specified.  

Ray

**Comment by smalers** [comment]
I had an exchange awhile back with someone that was having trouble recompiling StateMod on a newer version of Linux.  I suggested that they just use the old StateMod executable and that worked.  This was at the time that we were updating the software.

Perhaps enough time has passed that they can successfully compile with the latest code and `makefile`.

Or, just download the latest executable and try running that, with no need to recompile.  Doing this should be a simple test.

**Comment by rg727** [comment]
Hi Steve, I believe the exchange you had was with my colleague. The old Statemod executable works for the Upper Colorado and Gunnison but not with the San Juan dataset. I just tried to download the latest version of the code and recompile on our cluster (version: CentOS Linux 7), and this is the error I am getting. I followed the steps in the README listed here as well: https://github.com/OpenCDSS/cdss-app-statemod-fortran/tree/master/src/main/fortran

![image](https://user-images.githubusercontent.com/31748312/153281433-74bec624-bb0d-421d-baf0-d7c49336b308.png)

**Comment by Rayrbennett** [comment]
Steve, sounds like he has an old version.  15.X). I like your recommendation. I’ll stay out of this from here unless you ask for help.

**Comment by smalers** [comment]
I was having a lot of trouble for a while with different developers having different spelling of files, which is why everything should have been converted to lowercase in the repository, but it gets tricky depending on what was already on your computer.  This issue was due to primary development occurring on Windows (even though Linux-like MinGW is used).  Can you confirm that the file in the `makefile` for `flowres` matches the case of the file in your folder?  It may be necessary for you to rename the source file to all lowercase.  My point is, make the file referenced in the `makefile` match the name of the file in your folder.  If there is a problem, I'm interested in that and may need to fix in the repository.

Option 2 as I have said, is just download and run StateMod 17x from the following:

[https://opencdss.state.co.us/statemod/](https://opencdss.state.co.us/statemod/)

**Comment by macphersonbr** [comment]
I don't believe she can download a compiled version from https://opencdss.state.co.us/statemod/ because she is using a Linux cluster for her work. Steve's first suggestion of checking 'flowres' filename and case in the 'makefile' makes sense to me.

**Comment by rg727** [comment]
Hi everyone, thank you for the suggestions! I got it all working now on our cluster, but here are the things I needed to fix: 

1) The flowres files and some others were capitalized, so I went ahead and changed those to lowercase
2) I had to remove the -static flag (I see that this was not recommended, but the only way that I could compile on our cluster) 

I was able to run the San Juan dataset successfully through using the executable made after these changes.

**Comment by smalers** [comment]
Yes, I will fix the capitalization.  When working on a Windows computer this usually involves removing the old file so that it is gone once and for all, and then adding back with the appropriate case.  Or, rename to a completely different name and then rename again.  Otherwise Windows treats them the same.

**Comment by Rayrbennett** [comment]
Steve,
flowres.for, outwe.for & the makefile all have lower case file names.  
Ray

**Comment by smalers** [comment]
I cloned the repository into a clean folder and ran:

```
ls *[A-Z]*

AM.bat
AUTOMAKE.RSP
FlowRes.for
README.md
outWW.for
```

The two source files had slipped through.  I did two commits to rename the `.for` files to lowercase.  Note that internally Git treats these as the same files since the contents and hash of the file did not change.  I did not change the version number since this did not change any of the source code contents.

It is possible to do a check in the `makefile` to make sure this does not happen again.  I'll add a separate issue for that.

I'm closing this issue.
